-- AlterTable
ALTER TABLE "alerts" ADD COLUMN     "metadata" JSONB NOT NULL DEFAULT '{}',
ADD COLUMN     "severity" TEXT NOT NULL DEFAULT 'WARNING',
ADD COLUMN     "source" TEXT;

-- AlterTable
ALTER TABLE "channels" ADD COLUMN     "enabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "events" TEXT[] DEFAULT ARRAY['ALERT_CREATED', 'ALERT_RESOLVED']::TEXT[],
ADD COLUMN     "service_ids" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
