export const WS_EVENTS = {
  CHECK_UPDATE: 'CHECK_UPDATE',
  ALERT_CREATED: 'ALERT_CREATED',
  ALERT_RESOLVED: 'ALERT_RESOLVED',
  SERVICE_UPDATED: 'SERVICE_UPDATED',
  USER_UPDATED: 'USER_UPDATED',
  WIDGET_OUTPUT: 'WIDGET_OUTPUT',
  WIDGET_LAYOUT_UPDATED: 'WIDGET_LAYOUT_UPDATED',
} as const;

export type WsEvent = (typeof WS_EVENTS)[keyof typeof WS_EVENTS];
